### ISSUE TITLE
bug: the expanded dropdown menu should automatically collapse instead of becoming ugly when the user increases the window size

### ISSUE THREAD

**Issue by PlutoniumSoup** [move-fast-and-break-things/mfbt.community#38]
Demonstration of the issue:

https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/145541424/34363c13-47bd-4df2-a192-b94221dc5e9d

**Comment by rahul-p19** [comment]
I can work on this.

**Comment by chaitanya-bhargava** [comment]
I would like to work on this issue!

**Comment by yurijmikhalevich** [comment]
@rahul-p19, thank you for reaching out! Assigned the issue to you. Let me know if you have any questions 😄 

@chaitanya-bhargava, thank you for reaching out :) I have assigned the issue to @rahul-p19 because they commented on it first. Let me know if you would love to take any other issue on the list: https://github.com/move-fast-and-break-things/mfbt.community/issues.
